add Kibana healthcheck
georchestra/docker pull request #184
Opened 2023-04-03 15:26 UTC by jeanmi151

cf issue : https://github.com/georchestra/docker/issues/182

2023-04-03 15:31 UTC, edevosc2c requested changes

2023-04-03 15:31 UTC, edevosc2c commented on docker-compose.yml
> +      test: ["CMD-SHELL", "curl -s -f http://kibana:5601/api/status >/dev/null || exit 1"]
`http://localhost:5601/api/status` is IMO much better because it's using localhost instead of the service name

2023-04-04 07:20 UTC, edevosc2c approved these changes

2023-04-04 07:25 UTC, jahow commented
thanks for the change, have you confirmed that this URL answers correctly when kibana is up? when trying some stuff with it I couldn't find an unauthorized url that would give me a positive answer to do a healthcheck, but maybe I missed this one

2023-04-04 08:34 UTC, jeanmi151 commented
> e you confirmed that this URL answers correctly when kibana is up? when trying some stuff with it I couldn't find an unauthorized url that would give me a positive answer to do a healthcheck, bu

yes I checked (I connected to the container and curl this url ) that why I made another commit : f1341279210852ef3590793c9b1a5191c0ab32cf

2023-04-04 08:37 UTC, merged